version: "3.8"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    links:
      - php
     # - dbhost
    volumes:
      - ./conf/app.conf:/etc/nginx/conf.d/app.conf
      - ./app:/var/www/html

  php:
    build: php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    links:
      - dbhost
      

  dbhost:
    #build: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${password_root}"
      MYSQL_DATABASE: "${database}"
      MYSQL_USER: "${dbuser}"
      MYSQL_PASSWORD: "${password}"
    volumes:
      - ./db_conf:/var/lib/mysql


volumes:
  app:
  conf:
  db_conf:
 
  