version: "3.8"
services:

  nginxproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data_Nginx:/data
      - ./letsencrypt:/etc/letsencrypt  


  web:
    image: nginx:alpine
    ports:
      - "8081:80"
      - "4433:443"
    depends_on:
      - php
      - mysqlserver
    links:
      - php
    restart: always
    volumes:
      - ./conf/app.conf:/etc/nginx/conf.d/app.conf
      - ./app:/var/www/html
      

  php:
    image: php:7.4-fpm
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini 
    links:
      - mysqlserver
      

  mysqlserver:
    #build: mysql
    image: mysql:8.0
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${PASSWORD_ROOT}"
      MYSQL_DATABASE: "${DATABASE}"
      MYSQL_USER: "${DBUSER}"
      MYSQL_PASSWORD: "${DBPASSWORD}"
    volumes:
      - ./db_dados:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:apache
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysqlserver
    links:
      - mysqlserver

volumes:
  app:
  conf:
  db_dados:
 
  