name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: Ubuntu

    steps:
    - uses: actions/checkout@v2
    - name: Build Imagem PHP
      run: docker build ./php --tag php:$(date +%s)
