name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Imagem mysql
      run: docker build mysql --tag MySQL:$(date +%s)
    - name: Build Imagem PHP
      run: docker build php --tag PHP:$(date +%s)
